all:
  hosts:
    kano:
      ansible_host: '192.168.0.101'
      # ansible_host: 'www.gxiang.com.tw'
      ansible_user: 'pi'
      ansible_password: 'kano'
      # ansible_port: 10022
      # ansible_user: 'pi'
      # ansible_password: 'kano'
    